# Generated by Django 6.0 on 2025-12-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_requesthistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="suitability",
        ),
        migrations.AddField(
            model_name="portaluser",
            name="pin_code",
            field=models.CharField(
                default="0000", help_text="4-digit PIN for login", max_length=4
            ),
        ),
        migrations.AddField(
            model_name="portaluser",
            name="reading_centre_code",
            field=models.CharField(
                blank=True,
                help_text="Lab reading centre code",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="sample_suitability",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="report",
            name="suitability_reason",
            field=models.TextField(
                blank=True, help_text="Specify reason if suitability is No"
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="on_meds",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="report",
            name="quality",
            field=models.CharField(
                choices=[("Good", "Good"), ("Moderate", "Moderate"), ("Bad", "Bad")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="impression",
            field=models.CharField(
                choices=[
                    ("Bacterial", "Bacterial"),
                    ("Fungal", "Fungal"),
                    ("Acanthamoeba", "Acanthamoeba"),
                    ("Pythium", "Pythium"),
                    ("Viral", "Viral"),
                    ("Others", "Others"),
                ],
                default="Bacterial",
                max_length=50,
            ),
        ),
    ]
