# Generated by Django 6.0 on 2025-12-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_report_suitability_portaluser_pin_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="duration",
        ),
        migrations.AddField(
            model_name="request",
            name="duration_unit",
            field=models.CharField(
                choices=[
                    ("Days", "Days"),
                    ("Weeks", "Weeks"),
                    ("Months", "Months"),
                    ("Years", "Years"),
                ],
                default="Days",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="duration_value",
            field=models.PositiveIntegerField(default=1, help_text="Duration value"),
        ),
        migrations.AlterField(
            model_name="request",
            name="eye",
            field=models.CharField(
                choices=[
                    ("OD", "Right Eye (OD)"),
                    ("OS", "Left Eye (OS)"),
                    ("OU", "Both Eyes (OU)"),
                    ("NA", "Not Applicable (NA)"),
                ],
                default="OD",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="sample",
            field=models.CharField(
                choices=[
                    ("Corneal Scraping", "Corneal Scraping"),
                    ("Conjunctival Swab", "Conjunctival Swab"),
                    ("Tear Film", "Tear Film"),
                    ("Contact Lens", "Contact Lens"),
                    ("Eyelid", "Eyelid"),
                    ("Other", "Other"),
                ],
                default="Corneal Scraping",
                max_length=50,
            ),
        ),
    ]
