# Generated by Django 6.0 on 2025-12-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_request_duration_request_duration_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="meds",
        ),
        migrations.AddField(
            model_name="request",
            name="meds_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Antibiotics", "Antibiotics"),
                    ("Antifungals", "Antifungals"),
                    ("Antiviral", "Antiviral"),
                    ("Steroid", "Steroid"),
                    ("Others", "Others (Text)"),
                ],
                default="",
                help_text="Type of medication",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="meds_custom",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Custom medication name (for Others category)",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="on_meds",
            field=models.BooleanField(
                default=False, help_text="Patient is on prior medications"
            ),
        ),
    ]
